import React from 'react';
import { 
  Stars, 
  Mail, 
  UserPlus, 
  ListPlus, 
  ShoppingCart, 
  TrendingUp, 
  Phone,
  Search,
  History,
  AlertCircle,
  Sparkles,
  Zap,
  CheckCircle2,
  ShieldCheck,
  CalendarCheck
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { cn } from '@/src/lib/utils';
import { Lead, Signal, HunterPick, Deal, RepPerformance } from '@/src/types';
import { elenaDeals } from '@/src/lib/mockData';
import { useDemoData } from '@/src/context/DemoDataContext';
import HunterCommand from './HunterCommand';
import HunterAgent from './HunterAgent';
import OutreachModal from './OutreachModal';

interface DashboardProps {
  onHunterCommand: (accountName: string) => void;
}

import { handleEmailOutreach } from '@/src/lib/outreachUtils';

export default function Dashboard({ onHunterCommand }: DashboardProps) {
  const { asLeads, asPicks } = useDemoData();
  const [selectedPick, setSelectedPick] = React.useState<HunterPick | null>(null);
  const [initialPlatform, setInitialPlatform] = React.useState<'email' | 'linkedin'>('email');

  const openLeadOutreach = (lead: Lead, platform: 'email' | 'linkedin') => {
    const mappedPick: HunterPick = {
      id: `lead-${lead.id}`,
      name: lead.name,
      company: lead.company,
      urgency: lead.score >= 90 ? 'High Priority Lead' : 'New Inbound Lead',
      signal: lead.source,
      draft: '', // Will be generated by modal
      time: 'Just now',
      lastContact: 'Never',
      type: 'interest'
    };
    setInitialPlatform(platform);
    setSelectedPick(mappedPick);
  };
  
  const leads = asLeads();
  const hunterPicks = asPicks();

  const totalPipeline = elenaDeals.reduce((sum, d) => sum + d.value, 0);
  const activeSequences = Math.floor(elenaDeals.length * 1.5);
  const povSuccessRate = Math.round((elenaDeals.filter(d => d.povSuccess).length / elenaDeals.length) * 100);
  const pipelineFidelity = Math.round((elenaDeals.filter(d => d.validated).length / elenaDeals.length) * 100);

  return (
    <div className="max-w-7xl mx-auto space-y-10">
      {/* Header & Global Stats */}
      <section className="flex flex-col lg:flex-row lg:items-end justify-between gap-6">
        <div>
          <h1 className="text-4xl font-black text-on-background tracking-tighter font-headline mb-2">Prospecting Command Center</h1>
          <p className="text-slate-500 font-label">Netskope Growth OS: Reclaiming field capacity via system-enabled intelligence.</p>
        </div>
        <div className="flex gap-4">
          <div className="bg-surface-container-low px-6 py-4 rounded-2xl flex flex-col items-start gap-1">
            <span className="text-[10px] font-label uppercase tracking-widest text-secondary font-bold">Total Pipeline</span>
            <span className="text-2xl font-black font-headline text-on-background">${(totalPipeline / 1000000).toFixed(1)}M</span>
          </div>
          <div className="bg-surface-container-low px-6 py-4 rounded-2xl flex flex-col items-start gap-1">
            <span className="text-[10px] font-label uppercase tracking-widest text-primary font-bold">Active Sequences</span>
            <span className="text-2xl font-black font-headline text-on-background">{activeSequences}</span>
          </div>
        </div>
      </section>

      {/* Hunter Command Center */}
      <section className="bg-slate-50 p-8 rounded-[3rem] border border-slate-100 shadow-sm">
        <div className="flex flex-col items-center text-center mb-8">
          <div className="p-3 bg-primary/10 rounded-2xl text-primary mb-4">
            <Sparkles size={32} />
          </div>
          <h2 className="text-2xl font-black font-headline tracking-tight mb-2">Netskope Hunter Agent</h2>
          <p className="text-sm text-slate-500 font-label max-w-md">Execute the 11-item Hunter Playbook automatically. Eliminate manual research and reclaim field capacity.</p>
        </div>
        <HunterCommand onAccountSelect={(acc) => onHunterCommand(acc.name)} />
      </section>

      {/* Seller Performance Indicators */}
      <section className="grid grid-cols-1 md:grid-cols-4 gap-6">
        {[
          { label: 'Pipeline Fidelity', value: `${pipelineFidelity}%`, target: 'System-Validated', icon: ShieldCheck, color: 'text-primary', bg: 'bg-cyan-50' },
          { label: 'Pipeline Goal', value: '104%', target: 'vs. Q3 Quota', icon: TrendingUp, color: 'text-emerald-600', bg: 'bg-emerald-50' },
          { label: 'POV Success Rate', value: `${povSuccessRate}%`, target: 'Technical Wins', icon: CheckCircle2, color: 'text-indigo-600', bg: 'bg-indigo-50' },
          { label: 'Meetings Booked', value: '12', target: 'This Week', icon: CalendarCheck, color: 'text-amber-600', bg: 'bg-amber-50' },
        ].map((metric, idx) => (
          <div key={idx} className={cn("p-6 rounded-3xl flex flex-col gap-2", metric.bg)}>
            <div className="flex items-center justify-between">
              <metric.icon className={metric.color} size={20} />
              <span className="text-[10px] font-bold font-label uppercase tracking-wider text-slate-400">{metric.target}</span>
            </div>
            <div>
              <div className={cn("text-3xl font-black font-headline", metric.color)}>{metric.value}</div>
              <div className="text-xs font-label text-slate-500 font-medium">{metric.label}</div>
            </div>
          </div>
        ))}
      </section>

      {/* High-Value Inbound Leads */}
      <section className="space-y-4">
        <div className="flex items-center justify-between px-2">
          <h3 className="font-headline font-bold text-xl flex items-center gap-2">
            <Stars className="text-tertiary" size={24} />
            High-Value Inbound Leads
          </h3>
          <div className="flex items-center gap-2">
            <span className="flex h-2 w-2 rounded-full bg-red-500 animate-pulse"></span>
            <span className="text-xs font-label text-red-500 font-bold uppercase">{leads.filter(l => l.source === 'Demo Request' || l.tags?.includes('Demo Request')).length || leads.length} New Requests</span>
          </div>
        </div>
        <div className="bg-white rounded-[2rem] border border-slate-100 shadow-sm overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-left">
              <thead>
                <tr className="bg-slate-50/50">
                  <th className="px-6 py-3 text-[10px] font-black font-label uppercase tracking-widest text-slate-400">Contact</th>
                  <th className="px-6 py-3 text-[10px] font-black font-label uppercase tracking-widest text-slate-400">Company</th>
                  <th className="px-6 py-3 text-[10px] font-black font-label uppercase tracking-widest text-slate-400">Score</th>
                  <th className="px-6 py-3 text-[10px] font-black font-label uppercase tracking-widest text-slate-400">Tags</th>
                  <th className="px-6 py-3 text-[10px] font-black font-label uppercase tracking-widest text-slate-400 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-50">
                {leads.map((lead) => (
                  <tr key={lead.id} className="hover:bg-slate-50/50 transition-colors group">
                    <td className="px-6 py-4">
                      <div className="flex items-center gap-3">
                        <div className="h-8 w-8 rounded-full bg-tertiary/10 flex items-center justify-center text-tertiary font-bold text-xs">
                          {lead.initials}
                        </div>
                        <div>
                          <div className="text-sm font-bold text-on-background">{lead.name}</div>
                          <div className="text-[10px] text-slate-500 font-label">{lead.role}</div>
                        </div>
                      </div>
                    </td>
                    <td className="px-6 py-4">
                      <div className="text-sm font-medium text-slate-700">{lead.company}</div>
                    </td>
                    <td className="px-6 py-4">
                      <div className="flex items-center gap-2">
                        <span className={cn(
                          "text-sm font-black font-headline",
                          lead.score >= 90 ? "text-tertiary" : "text-slate-600"
                        )}>
                          {lead.score}
                        </span>
                        <div className="w-12 h-1 bg-slate-100 rounded-full overflow-hidden">
                          <div 
                            className="h-full bg-tertiary rounded-full"
                            style={{ width: `${lead.score}%` }}
                          />
                        </div>
                      </div>
                    </td>
                    <td className="px-6 py-4">
                      <div className="flex gap-2">
                        {lead.tags.map((tag) => (
                          <span
                            key={tag}
                            className={cn(
                              "px-2 py-0.5 rounded-full text-[9px] font-bold font-label uppercase tracking-tighter",
                              tag === 'Demo Request' || tag === 'Contact Us' 
                                ? "bg-red-100 text-red-700" 
                                : "bg-slate-100 text-slate-500"
                            )}
                          >
                            {tag}
                          </span>
                        ))}
                      </div>
                    </td>
                    <td className="px-6 py-4 text-right">
                      <div className="flex items-center justify-end gap-2">
                        <button 
                          onClick={() => openLeadOutreach(lead, 'email')}
                          className="p-1.5 rounded-lg hover:bg-primary/10 hover:text-primary text-slate-400 transition-all"
                        >
                          <Mail size={16} />
                        </button>
                        <button 
                          onClick={() => openLeadOutreach(lead, 'linkedin')}
                          className="p-1.5 rounded-lg hover:bg-[#0077b5]/10 hover:text-[#0077b5] text-slate-400 transition-all"
                        >
                          <UserPlus size={16} />
                        </button>
                        <button 
                          onClick={() => onHunterCommand(lead.company)}
                          className="p-1.5 rounded-lg hover:bg-tertiary/10 hover:text-tertiary text-slate-400 transition-all"
                          title="Execute Hunter"
                        >
                          <Sparkles size={16} />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </section>

      {/* Combined Hunter Picks & Purchasing Signals */}
      <section className="space-y-6">
        <div className="flex items-center justify-between px-2">
          <div className="flex flex-col">
            <h3 className="font-headline font-bold text-2xl flex items-center gap-3">
              <Sparkles className="text-primary" size={28} />
              Hunter Picks: Priority Outreach
            </h3>
            <p className="text-xs font-label text-slate-500 mt-1">System-identified high-conviction signals. Refreshes in 14h 22m.</p>
          </div>
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-2 px-3 py-1.5 bg-cyan-50 border border-cyan-100 rounded-xl">
              <span className="flex h-2 w-2 rounded-full bg-cyan-500 animate-pulse"></span>
              <span className="text-[10px] font-black font-label text-cyan-700 uppercase tracking-widest">{hunterPicks.length} Active Picks</span>
            </div>
          </div>
        </div>

        <div className="bg-white rounded-[2.5rem] border border-slate-100 shadow-sm overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-left">
              <thead>
                <tr className="bg-slate-50/50">
                  <th className="px-8 py-4 text-[10px] font-black font-label uppercase tracking-widest text-slate-400">Contact & Company</th>
                  <th className="px-8 py-4 text-[10px] font-black font-label uppercase tracking-widest text-slate-400">Signal</th>
                  <th className="px-8 py-4 text-[10px] font-black font-label uppercase tracking-widest text-slate-400">Last Contact</th>
                  <th className="px-8 py-4 text-[10px] font-black font-label uppercase tracking-widest text-slate-400 text-right">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-50">
                {hunterPicks.map((pick) => (
                  <tr key={pick.id} className="hover:bg-slate-50/50 transition-colors group">
                    <td className="px-8 py-5">
                      <div className="flex items-center gap-4">
                        <div className="h-10 w-10 rounded-xl overflow-hidden border border-slate-100 shadow-sm">
                          <img 
                            src={`https://picsum.photos/seed/${pick.name}/40/40`} 
                            alt={pick.name} 
                            referrerPolicy="no-referrer"
                          />
                        </div>
                        <div>
                          <div className="text-sm font-bold text-on-background">{pick.name}</div>
                          <div className="text-[10px] font-black font-label text-primary uppercase tracking-tight">{pick.company}</div>
                        </div>
                      </div>
                    </td>
                    <td className="px-8 py-5">
                      <div className="flex flex-col gap-1">
                        <span className={cn(
                          "inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg text-[10px] font-black font-label uppercase tracking-wider w-fit",
                          pick.type === 'funding' ? "bg-amber-100 text-amber-700" :
                          pick.type === 'interest' ? "bg-cyan-100 text-cyan-700" :
                          pick.type === 'hire' ? "bg-blue-100 text-blue-700" :
                          "bg-slate-100 text-slate-600"
                        )}>
                          {pick.signal}
                        </span>
                        <p className="text-[11px] text-slate-500 font-label italic line-clamp-1 max-w-xs">{pick.draft}</p>
                      </div>
                    </td>
                    <td className="px-8 py-5">
                      <div className="flex flex-col">
                        <span className={cn(
                          "text-xs font-bold",
                          pick.lastContact === 'Never' ? "text-emerald-600" : "text-slate-600"
                        )}>{pick.lastContact}</span>
                        <span className="text-[9px] font-medium text-slate-400 uppercase tracking-tighter">via System</span>
                      </div>
                    </td>
                    <td className="px-8 py-5 text-right">
                      <button 
                        onClick={() => setSelectedPick(pick)}
                        className="px-5 py-2 bg-primary text-white text-[11px] font-black uppercase tracking-widest rounded-xl hover:opacity-90 transition-all shadow-lg shadow-primary/10"
                      >
                        Send Message
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </section>

      <OutreachModal 
        pick={selectedPick} 
        initialPlatform={initialPlatform}
        onClose={() => setSelectedPick(null)} 
      />
    </div>
  );
}
