"""
SFDC-scenario seed: replaces inbound_leads with curated records that demonstrate
the Lead → Contact progression as it would look in Salesforce.

Three stages:
  Stage 1 – Pure Lead    : no account in CRM, no meeting
  Stage 2 – Lead (warm)  : account exists in CRM, meeting not yet booked
  Stage 3 – Contact      : account exists + meeting secured → promotes to Contact

Run:
  cd backend && uv run python -m app.seed.sfdc_scenario
"""

import asyncio
import uuid
from datetime import datetime, timedelta, timezone

from sqlalchemy import delete, text
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import sessionmaker

from app.config import settings
import app.models  # noqa: F401 — registers all ORM classes so relationships resolve
from app.models.inbound_lead import InboundLead

# ---------------------------------------------------------------------------
# Curated SFDC records
# ---------------------------------------------------------------------------

_NOW = datetime.now(timezone.utc)


def _ts(hours_ago: float) -> datetime:
    return _NOW - timedelta(hours=hours_ago)


RECORDS = [
    # ──────────────────────────────────────────────────────────────────────────
    # STAGE 1 — Pure Leads (no account in CRM)
    # ──────────────────────────────────────────────────────────────────────────
    {
        "id": str(uuid.uuid4()),
        "source": "web_form",
        "source_detail": "Website Contact Form",
        "captured_at": _ts(2),
        "first_name": "Marcus",
        "last_name": "Webb",
        "email": "marcus.webb@stratahealth.com",
        "phone": "(512) 348-2291",
        "company": "Strata Health Solutions",
        "title": "Director of IT Security",
        "company_size": "501-1000",
        "industry": "Healthcare",
        "hq_city": "Austin",
        "hq_state": "TX",
        "hq_country": "United States",
        "annual_revenue": 180_000_000,
        "message": "We are evaluating Zero Trust solutions to replace our legacy VPN. Looking for something that scales with our remote workforce.",
        "product_interest": "ZTNA",
        "lead_tier": "SDR_WORTHY",
        "is_competitor": False,
        "is_duplicate": False,
        "account_match": False,
        "meeting_secured": False,
        "marketo_signal": "B2",
        "marketo_program": "2024-Q2-ZTNA-Webinar",
        "persona_tier": "Director | Manager",
        "intent_signal": "High",
        "priority_score": 78,
        "recommended_action": "Immediate SDR outreach",
        "campaign_sequence": "Enterprise ZTNA Discovery",
        "sdr_ready_notes": "High intent — attended ZTNA webinar and downloaded Zero Trust guide. No matching account in SFDC. Create new account and sequence immediately.",
        "processing_status": "done",
        "processed": True,
        "processed_at": _ts(1.5),
        "assigned_territory": "Central",
        "assigned_to_role": "sdr",
        "routing_queue": "primary",
        "contact_validated": True,
        "is_existing_customer": False,
        "data_quality_score": 0.91,
        "agent_notes": None,
        "created_at": _ts(2),
    },
    {
        "id": str(uuid.uuid4()),
        "source": "marketo",
        "source_detail": "SASE Summit 2024 Registration",
        "captured_at": _ts(5),
        "first_name": "Priya",
        "last_name": "Nair",
        "email": "p.nair@vertexlogistics.io",
        "phone": None,
        "company": "Vertex Logistics",
        "title": "VP of Information Technology",
        "company_size": "1001-5000",
        "industry": "Logistics & Supply Chain",
        "hq_city": "Columbus",
        "hq_state": "OH",
        "hq_country": "United States",
        "annual_revenue": 420_000_000,
        "message": None,
        "product_interest": "SASE",
        "lead_tier": "SDR_WORTHY",
        "is_competitor": False,
        "is_duplicate": False,
        "account_match": False,
        "meeting_secured": False,
        "marketo_signal": "A3",
        "marketo_program": "2024-SASE-Summit-Registration",
        "persona_tier": "VP | Director",
        "intent_signal": "Medium",
        "priority_score": 72,
        "recommended_action": "SDR outreach within 24h",
        "campaign_sequence": "Mid-Market SASE Play",
        "sdr_ready_notes": "Registered for SASE Summit — VP title at a 1000+ logistics firm. Logistics vertical is strong SASE use case. No account in SFDC.",
        "processing_status": "done",
        "processed": True,
        "processed_at": _ts(4),
        "assigned_territory": "Central",
        "assigned_to_role": "sdr",
        "routing_queue": "primary",
        "contact_validated": True,
        "is_existing_customer": False,
        "data_quality_score": 0.87,
        "agent_notes": None,
        "created_at": _ts(5),
    },
    {
        "id": str(uuid.uuid4()),
        "source": "web_form",
        "source_detail": "Free Trial Request",
        "captured_at": _ts(8),
        "first_name": "Derek",
        "last_name": "Okonkwo",
        "email": "derek.okonkwo@pinnacleinsure.com",
        "phone": "(404) 774-1023",
        "company": "Pinnacle Insurance Group",
        "title": "CISO",
        "company_size": "501-1000",
        "industry": "Insurance",
        "hq_city": "Atlanta",
        "hq_state": "GA",
        "hq_country": "United States",
        "annual_revenue": 310_000_000,
        "message": "We need to modernize our network security posture ahead of our upcoming SOC 2 Type II audit. Interested in seeing a demo.",
        "product_interest": "ZTNA",
        "lead_tier": "RSM_READY",
        "is_competitor": False,
        "is_duplicate": False,
        "account_match": False,
        "meeting_secured": False,
        "marketo_signal": "A1",
        "marketo_program": "2024-Q3-Free-Trial",
        "persona_tier": "C-Suite | VP",
        "intent_signal": "High",
        "priority_score": 92,
        "recommended_action": "RSM direct outreach — executive buyer",
        "campaign_sequence": "CISO High-Touch ZTNA",
        "sdr_ready_notes": "CISO-level, High activity signal, explicitly requested demo for upcoming audit. No account in SFDC — prioritize account creation.",
        "processing_status": "done",
        "processed": True,
        "processed_at": _ts(7),
        "assigned_territory": "Southeast",
        "assigned_to_role": "rsm",
        "routing_queue": "rsm",
        "contact_validated": True,
        "is_existing_customer": False,
        "data_quality_score": 0.96,
        "agent_notes": None,
        "created_at": _ts(8),
    },
    {
        "id": str(uuid.uuid4()),
        "source": "linkedin",
        "source_detail": "LinkedIn Lead Gen Form — VPN Replacement Guide",
        "captured_at": _ts(14),
        "first_name": "Tanya",
        "last_name": "Flores",
        "email": "tflores@brightsideretail.com",
        "phone": None,
        "company": "Brightside Retail Corp",
        "title": "Network Security Manager",
        "company_size": "1001-5000",
        "industry": "Retail",
        "hq_city": "Dallas",
        "hq_state": "TX",
        "hq_country": "United States",
        "annual_revenue": 890_000_000,
        "message": None,
        "product_interest": "SWG",
        "lead_tier": "SDR_WORTHY",
        "is_competitor": False,
        "is_duplicate": False,
        "account_match": False,
        "meeting_secured": False,
        "marketo_signal": "B1",
        "marketo_program": "2024-LI-VPN-Replacement-Guide",
        "persona_tier": "Director | Manager",
        "intent_signal": "Medium",
        "priority_score": 65,
        "recommended_action": "SDR outreach — qualify budget and timeline",
        "campaign_sequence": "VPN Replacement Track",
        "sdr_ready_notes": "Downloaded VPN Replacement Guide via LinkedIn. Large retail footprint = strong SWG use case. No SFDC account.",
        "processing_status": "done",
        "processed": True,
        "processed_at": _ts(13),
        "assigned_territory": "Southwest",
        "assigned_to_role": "sdr",
        "routing_queue": "primary",
        "contact_validated": True,
        "is_existing_customer": False,
        "data_quality_score": 0.82,
        "agent_notes": None,
        "created_at": _ts(14),
    },

    # ──────────────────────────────────────────────────────────────────────────
    # STAGE 2 — Lead with account match (account in SFDC, meeting not yet booked)
    # ──────────────────────────────────────────────────────────────────────────
    {
        "id": str(uuid.uuid4()),
        "source": "marketo",
        "source_detail": "Gartner SSE Magic Quadrant Content Download",
        "captured_at": _ts(18),
        "first_name": "Kevin",
        "last_name": "Nakamura",
        "email": "k.nakamura@harborfinancial.com",
        "phone": "(617) 555-0182",
        "company": "Harbor Financial Services",  # Account exists in SFDC
        "title": "Director of Cybersecurity",
        "company_size": "5000+",
        "industry": "Financial Services",
        "hq_city": "Boston",
        "hq_state": "MA",
        "hq_country": "United States",
        "annual_revenue": 2_100_000_000,
        "message": None,
        "product_interest": "ZTNA",
        "lead_tier": "RSM_READY",
        "is_competitor": False,
        "is_duplicate": False,
        "account_match": True,
        "meeting_secured": False,
        "marketo_signal": "A2",
        "marketo_program": "2024-Gartner-SSE-MQ-Download",
        "persona_tier": "VP | Director",
        "intent_signal": "High",
        "priority_score": 85,
        "recommended_action": "RSM outreach — account already in SFDC, new stakeholder",
        "campaign_sequence": "Enterprise SSE Launch",
        "sdr_ready_notes": "Account 'Harbor Financial Services' exists in SFDC (open opportunity). Kevin is a new inbound contact — downloaded Gartner SSE MQ. Route to RSM owning the account.",
        "processing_status": "done",
        "processed": True,
        "processed_at": _ts(17),
        "assigned_territory": "Northeast",
        "assigned_to_role": "rsm",
        "routing_queue": "rsm",
        "contact_validated": True,
        "is_existing_customer": False,
        "data_quality_score": 0.94,
        "agent_notes": None,
        "created_at": _ts(18),
    },
    {
        "id": str(uuid.uuid4()),
        "source": "web_form",
        "source_detail": "Website — Request a Demo",
        "captured_at": _ts(22),
        "first_name": "Sandra",
        "last_name": "Okafor",
        "email": "sandra.okafor@tritonmanufacturing.com",
        "phone": "(313) 446-7720",
        "company": "Triton Manufacturing",  # Account exists in SFDC
        "title": "VP of IT Infrastructure",
        "company_size": "1001-5000",
        "industry": "Manufacturing",
        "hq_city": "Detroit",
        "hq_state": "MI",
        "hq_country": "United States",
        "annual_revenue": 760_000_000,
        "message": "We went through a ransomware incident last year and our board is pushing us to modernize. We specifically want to evaluate ZTNA and SSE.",
        "product_interest": "ZTNA",
        "lead_tier": "RSM_READY",
        "is_competitor": False,
        "is_duplicate": False,
        "account_match": True,
        "meeting_secured": False,
        "marketo_signal": "A1",
        "marketo_program": "2024-Q3-Demo-Request",
        "persona_tier": "C-Suite | VP",
        "intent_signal": "High",
        "priority_score": 90,
        "recommended_action": "RSM direct outreach — high urgency, board-driven initiative",
        "campaign_sequence": "CISO High-Touch ZTNA",
        "sdr_ready_notes": "Ransomware survivor, board mandate, VP title. Account 'Triton Manufacturing' in SFDC with prior activity. Meeting not yet scheduled — priority for this week.",
        "processing_status": "done",
        "processed": True,
        "processed_at": _ts(21),
        "assigned_territory": "Midwest",
        "assigned_to_role": "rsm",
        "routing_queue": "rsm",
        "contact_validated": True,
        "is_existing_customer": False,
        "data_quality_score": 0.97,
        "agent_notes": None,
        "created_at": _ts(22),
    },
    {
        "id": str(uuid.uuid4()),
        "source": "marketo",
        "source_detail": "Zero Trust Maturity Assessment Tool",
        "captured_at": _ts(30),
        "first_name": "Brian",
        "last_name": "Castellano",
        "email": "b.castellano@nexusenergy.com",
        "phone": None,
        "company": "Nexus Energy Partners",  # Account exists in SFDC
        "title": "Senior Security Architect",
        "company_size": "1001-5000",
        "industry": "Energy & Utilities",
        "hq_city": "Houston",
        "hq_state": "TX",
        "hq_country": "United States",
        "annual_revenue": 1_400_000_000,
        "message": None,
        "product_interest": "ZTNA",
        "lead_tier": "SDR_WORTHY",
        "is_competitor": False,
        "is_duplicate": False,
        "account_match": True,
        "meeting_secured": False,
        "marketo_signal": "B2",
        "marketo_program": "2024-ZT-Maturity-Assessment",
        "persona_tier": "Director | Manager",
        "intent_signal": "Medium",
        "priority_score": 70,
        "recommended_action": "SDR outreach — technical influencer, account has RSM",
        "campaign_sequence": "GRC Compliance Track",
        "sdr_ready_notes": "Technical architect at known account 'Nexus Energy Partners'. Completed Zero Trust Maturity Assessment — score indicates early stage. Connect with RSM before outreach.",
        "processing_status": "done",
        "processed": True,
        "processed_at": _ts(29),
        "assigned_territory": "Southwest",
        "assigned_to_role": "sdr",
        "routing_queue": "primary",
        "contact_validated": True,
        "is_existing_customer": False,
        "data_quality_score": 0.88,
        "agent_notes": None,
        "created_at": _ts(30),
    },
    {
        "id": str(uuid.uuid4()),
        "source": "event",
        "source_detail": "RSA Conference 2024 — Booth Scan",
        "captured_at": _ts(36),
        "first_name": "Angela",
        "last_name": "Merritt",
        "email": "amerritt@cascadehealth.org",
        "phone": "(503) 228-4401",
        "company": "Cascade Health Network",  # Account exists in SFDC
        "title": "CISO",
        "company_size": "5000+",
        "industry": "Healthcare",
        "hq_city": "Portland",
        "hq_state": "OR",
        "hq_country": "United States",
        "annual_revenue": 3_200_000_000,
        "message": "Interested in Netskope's HIPAA-compliant SASE offering. Will follow up after the conference.",
        "product_interest": "SASE",
        "lead_tier": "RSM_READY",
        "is_competitor": False,
        "is_duplicate": False,
        "account_match": True,
        "meeting_secured": False,
        "marketo_signal": "A2",
        "marketo_program": "2024-RSA-Booth-Scan",
        "persona_tier": "C-Suite | VP",
        "intent_signal": "High",
        "priority_score": 88,
        "recommended_action": "RSM outreach within 48h of event — hot lead",
        "campaign_sequence": "CISO High-Touch ZTNA",
        "sdr_ready_notes": "CISO badge scan at RSA, explicitly expressed interest in HIPAA SASE. Account 'Cascade Health Network' in SFDC. Meeting pending — RSM should reach out today.",
        "processing_status": "done",
        "processed": True,
        "processed_at": _ts(35),
        "assigned_territory": "West",
        "assigned_to_role": "rsm",
        "routing_queue": "rsm",
        "contact_validated": True,
        "is_existing_customer": False,
        "data_quality_score": 0.95,
        "agent_notes": None,
        "created_at": _ts(36),
    },

    # ──────────────────────────────────────────────────────────────────────────
    # STAGE 3 — Contacts (account exists + meeting secured → Contact in SFDC)
    # ──────────────────────────────────────────────────────────────────────────
    {
        "id": str(uuid.uuid4()),
        "source": "marketo",
        "source_detail": "Netskope Executive Dinner — Q2 2024",
        "captured_at": _ts(72),
        "first_name": "Robert",
        "last_name": "Chang",
        "email": "robert.chang@apexfingroup.com",
        "phone": "(212) 588-3347",
        "company": "Apex Financial Group",  # Account in SFDC, meeting booked
        "title": "Chief Information Security Officer",
        "company_size": "5000+",
        "industry": "Financial Services",
        "hq_city": "New York",
        "hq_state": "NY",
        "hq_country": "United States",
        "annual_revenue": 8_500_000_000,
        "message": "Met at executive dinner. Evaluating SASE for 12,000 employees across 40 offices. Decision timeline Q4 2024.",
        "product_interest": "SASE",
        "lead_tier": "RSM_READY",
        "is_competitor": False,
        "is_duplicate": False,
        "account_match": True,
        "meeting_secured": True,
        "marketo_signal": "A1",
        "marketo_program": "2024-Q2-Executive-Dinner",
        "persona_tier": "C-Suite | VP",
        "intent_signal": "High",
        "priority_score": 97,
        "recommended_action": "Convert to Contact — discovery call scheduled for next Tuesday",
        "campaign_sequence": "CIO Executive Nurture",
        "sdr_ready_notes": "Executive dinner attendee, CISO of $8.5B financial firm. Account in SFDC, discovery call booked. Converted to Contact — update SFDC opportunity stage.",
        "processing_status": "done",
        "processed": True,
        "processed_at": _ts(71),
        "assigned_territory": "Northeast",
        "assigned_to_role": "rsm",
        "routing_queue": "rsm",
        "contact_validated": True,
        "is_existing_customer": False,
        "data_quality_score": 0.99,
        "agent_notes": None,
        "created_at": _ts(72),
    },
    {
        "id": str(uuid.uuid4()),
        "source": "web_form",
        "source_detail": "Website — Request a Demo",
        "captured_at": _ts(96),
        "first_name": "Melissa",
        "last_name": "Harrington",
        "email": "m.harrington@bluecrossdigital.com",
        "phone": "(312) 701-2240",
        "company": "BlueCross Digital Health",  # Account in SFDC, meeting secured
        "title": "VP of Information Security",
        "company_size": "5000+",
        "industry": "Healthcare",
        "hq_city": "Chicago",
        "hq_state": "IL",
        "hq_country": "United States",
        "annual_revenue": 5_700_000_000,
        "message": "We are a healthcare payer moving to a cloud-first model and need HIPAA-compliant SSE. Requested a product demo.",
        "product_interest": "SSE",
        "lead_tier": "RSM_READY",
        "is_competitor": False,
        "is_duplicate": False,
        "account_match": True,
        "meeting_secured": True,
        "marketo_signal": "A1",
        "marketo_program": "2024-Q3-Demo-Request",
        "persona_tier": "C-Suite | VP",
        "intent_signal": "High",
        "priority_score": 95,
        "recommended_action": "Contact — demo scheduled, prepare HIPAA-specific talk track",
        "campaign_sequence": "Enterprise SSE Launch",
        "sdr_ready_notes": "Demo confirmed for this Friday. SFDC account updated, opportunity created at Stage 2. Prepare Healthcare SSE battlecard.",
        "processing_status": "done",
        "processed": True,
        "processed_at": _ts(95),
        "assigned_territory": "Midwest",
        "assigned_to_role": "rsm",
        "routing_queue": "rsm",
        "contact_validated": True,
        "is_existing_customer": False,
        "data_quality_score": 0.98,
        "agent_notes": None,
        "created_at": _ts(96),
    },
    {
        "id": str(uuid.uuid4()),
        "source": "event",
        "source_detail": "Gartner Security Summit — Speaking Session",
        "captured_at": _ts(120),
        "first_name": "James",
        "last_name": "Whitfield",
        "email": "j.whitfield@sterlingaerospace.com",
        "phone": "(310) 892-5503",
        "company": "Sterling Aerospace & Defense",  # Account in SFDC, meeting secured
        "title": "CIO",
        "company_size": "5000+",
        "industry": "Aerospace & Defense",
        "hq_city": "Los Angeles",
        "hq_state": "CA",
        "hq_country": "United States",
        "annual_revenue": 12_000_000_000,
        "message": "Approached after our ZTNA keynote. Evaluating vendors for a full SSE platform replacement. Engaged.",
        "product_interest": "SSE",
        "lead_tier": "RSM_READY",
        "is_competitor": False,
        "is_duplicate": False,
        "account_match": True,
        "meeting_secured": True,
        "marketo_signal": "A1",
        "marketo_program": "2024-Gartner-Security-Summit",
        "persona_tier": "C-Suite | VP",
        "intent_signal": "High",
        "priority_score": 99,
        "recommended_action": "Contact — executive sponsor confirmed, full evaluation underway",
        "campaign_sequence": "CISO High-Touch ZTNA",
        "sdr_ready_notes": "CIO of $12B A&D firm. SFDC account active, Stage 3 opportunity. Technical deep-dive scheduled for next week. Full evaluation underway.",
        "processing_status": "done",
        "processed": True,
        "processed_at": _ts(119),
        "assigned_territory": "West",
        "assigned_to_role": "rsm",
        "routing_queue": "rsm",
        "contact_validated": True,
        "is_existing_customer": False,
        "data_quality_score": 1.0,
        "agent_notes": None,
        "created_at": _ts(120),
    },
    {
        "id": str(uuid.uuid4()),
        "source": "marketo",
        "source_detail": "Netskope SASE Summit — Keynote Registration",
        "captured_at": _ts(144),
        "first_name": "Christine",
        "last_name": "Patel",
        "email": "cpatel@quantumlogisticsgroup.com",
        "phone": "(469) 334-8812",
        "company": "Quantum Logistics Group",  # Account in SFDC, meeting secured
        "title": "VP of Network Engineering",
        "company_size": "1001-5000",
        "industry": "Logistics & Supply Chain",
        "hq_city": "Dallas",
        "hq_state": "TX",
        "hq_country": "United States",
        "annual_revenue": 1_800_000_000,
        "message": None,
        "product_interest": "SASE",
        "lead_tier": "RSM_READY",
        "is_competitor": False,
        "is_duplicate": False,
        "account_match": True,
        "meeting_secured": True,
        "marketo_signal": "A2",
        "marketo_program": "2024-SASE-Summit-Keynote",
        "persona_tier": "C-Suite | VP",
        "intent_signal": "High",
        "priority_score": 91,
        "recommended_action": "Contact — follow-up call confirmed post-summit",
        "campaign_sequence": "Mid-Market SASE Play",
        "sdr_ready_notes": "Summit keynote attendee. Account 'Quantum Logistics Group' in SFDC with active opportunity. Post-summit call confirmed. Promoted to Contact.",
        "processing_status": "done",
        "processed": True,
        "processed_at": _ts(143),
        "assigned_territory": "Southwest",
        "assigned_to_role": "rsm",
        "routing_queue": "rsm",
        "contact_validated": True,
        "is_existing_customer": False,
        "data_quality_score": 0.96,
        "agent_notes": None,
        "created_at": _ts(144),
    },
]


# ---------------------------------------------------------------------------
# Runner
# ---------------------------------------------------------------------------

async def run() -> None:
    engine = create_async_engine(settings.DATABASE_URL, echo=False)
    Session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)  # noqa: N806

    async with Session() as session:
        # Wipe existing leads
        await session.execute(delete(InboundLead))
        await session.commit()
        print(f"Cleared inbound_leads table.")

        # Insert SFDC scenario records
        for rec in RECORDS:
            session.add(InboundLead(**rec))
        await session.commit()
        print(f"Inserted {len(RECORDS)} SFDC-scenario leads:")

        stage1 = [r for r in RECORDS if not r["account_match"]]
        stage2 = [r for r in RECORDS if r["account_match"] and not r["meeting_secured"]]
        stage3 = [r for r in RECORDS if r["account_match"] and r["meeting_secured"]]
        print(f"  Stage 1 — Pure Lead (no account match): {len(stage1)}")
        print(f"  Stage 2 — Lead w/ account match (no meeting): {len(stage2)}")
        print(f"  Stage 3 — Contact (account + meeting secured): {len(stage3)}")

    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(run())
