"""Seed data: 10 US territories + 200 accounts with HQ-accurate territory assignments."""

TERRITORY_SEEDS = [
    {
        "name": "Northwest",
        "description": "Washington, Oregon, Idaho, Alaska",
        "states_covered": "WA,OR,ID,AK",
    },
    {
        "name": "Northern California",
        "description": "San Francisco Bay Area, Silicon Valley, Sacramento Valley",
        "states_covered": "CA-N",
    },
    {
        "name": "Southern California",
        "description": "Los Angeles, San Diego, Orange County, Inland Empire",
        "states_covered": "CA-S",
    },
    {
        "name": "Southwest",
        "description": "Arizona, Nevada, New Mexico, Utah, Hawaii",
        "states_covered": "AZ,NV,NM,UT,HI",
    },
    {
        "name": "Mountain",
        "description": "Colorado, Wyoming, Montana",
        "states_covered": "CO,WY,MT",
    },
    {
        "name": "Great Plains",
        "description": "Oklahoma, Kansas, Nebraska, Minnesota, Iowa, Missouri, Wisconsin, Illinois, Michigan, Indiana, Ohio, Arkansas",
        "states_covered": "OK,KS,NE,MN,IA,MO,WI,IL,MI,IN,OH,AR",
    },
    {
        "name": "Southeast",
        "description": "Florida, Georgia, Alabama, Mississippi, Tennessee, South Carolina, North Carolina, Louisiana",
        "states_covered": "FL,GA,AL,MS,TN,SC,NC,LA",
    },
    {
        "name": "New England",
        "description": "Massachusetts, Connecticut, Rhode Island, Vermont, New Hampshire, Maine",
        "states_covered": "MA,CT,RI,VT,NH,ME",
    },
    {
        "name": "Northeast",
        "description": "New York, New Jersey, Pennsylvania, Delaware",
        "states_covered": "NY,NJ,PA,DE",
    },
    {
        "name": "Mid-Atlantic",
        "description": "Washington DC, Maryland, Virginia, West Virginia",
        "states_covered": "DC,MD,VA,WV",
    },
    {
        "name": "Texas",
        "description": "All of Texas — Dallas, Houston, Austin, San Antonio",
        "states_covered": "TX",
    },
]

# Maps company name → (territory_name, hq_city, hq_state)
ACCOUNT_TERRITORY_MAP: dict[str, tuple[str, str, str]] = {
    # ── Fortune 100 base companies ───────────────────────────────────────────────
    "Apple":                   ("Northern California", "Cupertino",         "CA"),
    "Microsoft":               ("Northwest",           "Redmond",           "WA"),
    "Alphabet":                ("Northern California", "Mountain View",     "CA"),
    "Amazon":                  ("Northwest",           "Seattle",           "WA"),
    "NVIDIA":                  ("Northern California", "Santa Clara",       "CA"),
    "Meta":                    ("Northern California", "Menlo Park",        "CA"),
    "Berkshire Hathaway":      ("Great Plains",        "Omaha",             "NE"),
    "Tesla":                   ("Texas",               "Austin",            "TX"),
    "Eli Lilly":               ("Great Plains",        "Indianapolis",      "IN"),
    "Broadcom":                ("Northern California", "San Jose",          "CA"),
    "JPMorgan Chase":          ("Northeast",           "New York",          "NY"),
    "UnitedHealth":            ("Great Plains",        "Minnetonka",        "MN"),
    "Visa":                    ("Northern California", "Foster City",       "CA"),
    "ExxonMobil":              ("Texas",               "Spring",            "TX"),
    "Johnson & Johnson":       ("Northeast",           "New Brunswick",     "NJ"),
    "Walmart":                 ("Southeast",           "Bentonville",       "AR"),
    "Mastercard":              ("Northeast",           "Purchase",          "NY"),
    "Procter & Gamble":        ("Great Plains",        "Cincinnati",        "OH"),
    "Home Depot":              ("Southeast",           "Atlanta",           "GA"),
    "Chevron":                 ("Northern California", "San Ramon",         "CA"),
    "AbbVie":                  ("Great Plains",        "North Chicago",     "IL"),
    "Merck":                   ("Northeast",           "Rahway",            "NJ"),
    "Costco":                  ("Northwest",           "Issaquah",          "WA"),
    "Adobe":                   ("Northern California", "San Jose",          "CA"),
    "Salesforce":              ("Northern California", "San Francisco",     "CA"),
    "PepsiCo":                 ("Northeast",           "Purchase",          "NY"),
    "Coca-Cola":               ("Southeast",           "Atlanta",           "GA"),
    "Netflix":                 ("Northern California", "Los Gatos",         "CA"),
    "Thermo Fisher":           ("New England",         "Waltham",           "MA"),
    "Cisco":                   ("Northern California", "San Jose",          "CA"),
    "Accenture":               ("Northeast",           "New York",          "NY"),
    "McDonald's":              ("Great Plains",        "Chicago",           "IL"),
    "Intel":                   ("Northern California", "Santa Clara",       "CA"),
    "Danaher":                 ("Mid-Atlantic",        "Washington",        "DC"),
    "Verizon":                 ("Northeast",           "New York",          "NY"),
    "NextEra Energy":          ("Southeast",           "Juno Beach",        "FL"),
    "Comcast":                 ("Northeast",           "Philadelphia",      "PA"),
    "Texas Instruments":       ("Texas",               "Dallas",            "TX"),
    "Wells Fargo":             ("Northern California", "San Francisco",     "CA"),
    "Nike":                    ("Northwest",           "Beaverton",         "OR"),
    "Intuit":                  ("Northern California", "Mountain View",     "CA"),
    "Amgen":                   ("Southern California", "Thousand Oaks",     "CA"),
    "IBM":                     ("Northeast",           "Armonk",            "NY"),
    "Medtronic":               ("Great Plains",        "Minneapolis",       "MN"),
    "Honeywell":               ("Southeast",           "Charlotte",         "NC"),
    "Oracle":                  ("Texas",               "Austin",            "TX"),
    "Morgan Stanley":          ("Northeast",           "New York",          "NY"),
    "Lowe's":                  ("Southeast",           "Mooresville",       "NC"),
    "AT&T":                    ("Texas",               "Dallas",            "TX"),
    "Union Pacific":           ("Great Plains",        "Omaha",             "NE"),
    "Boeing":                  ("Mid-Atlantic",        "Arlington",         "VA"),
    "Caterpillar":             ("Texas",               "Irving",            "TX"),
    "American Express":        ("Northeast",           "New York",          "NY"),
    "Goldman Sachs":           ("Northeast",           "New York",          "NY"),
    "Starbucks":               ("Northwest",           "Seattle",           "WA"),
    "ServiceNow":              ("Northern California", "Santa Clara",       "CA"),
    "BlackRock":               ("Northeast",           "New York",          "NY"),
    "Intuitive Surgical":      ("Northern California", "Sunnyvale",         "CA"),
    "Mondelez":                ("Great Plains",        "Chicago",           "IL"),
    "Applied Materials":       ("Northern California", "Santa Clara",       "CA"),
    "CVS Health":              ("New England",         "Woonsocket",        "RI"),
    "GE":                      ("New England",         "Boston",            "MA"),
    "Marsh & McLennan":        ("Northeast",           "New York",          "NY"),
    "Analog Devices":          ("New England",         "Wilmington",        "MA"),
    "Stryker":                 ("Great Plains",        "Kalamazoo",         "MI"),
    "Gilead Sciences":         ("Northern California", "Foster City",       "CA"),
    "Booking Holdings":        ("New England",         "Norwalk",           "CT"),
    "TJX Companies":           ("New England",         "Framingham",        "MA"),
    "Vertex Pharmaceuticals":  ("New England",         "Boston",            "MA"),
    "Progressive":             ("Great Plains",        "Mayfield Village",  "OH"),
    "Uber":                    ("Northern California", "San Francisco",     "CA"),
    "Airbnb":                  ("Northern California", "San Francisco",     "CA"),
    "Snowflake":               ("Northern California", "San Mateo",         "CA"),
    "Palantir":                ("Mountain",            "Denver",            "CO"),
    "CrowdStrike":             ("Texas",               "Austin",            "TX"),
    "Datadog":                 ("Northeast",           "New York",          "NY"),
    "Zscaler":                 ("Northern California", "San Jose",          "CA"),
    "Cloudflare":              ("Northern California", "San Francisco",     "CA"),
    "MongoDB":                 ("Northeast",           "New York",          "NY"),
    "Okta":                    ("Northern California", "San Francisco",     "CA"),
    "Twilio":                  ("Northern California", "San Francisco",     "CA"),
    "HubSpot":                 ("New England",         "Cambridge",         "MA"),
    "Zoom":                    ("Northern California", "San Jose",          "CA"),
    "Shopify":                 ("Northeast",           "New York",          "NY"),
    "Square":                  ("Northern California", "San Francisco",     "CA"),
    "PayPal":                  ("Northern California", "San Jose",          "CA"),
    "Stripe":                  ("Northern California", "San Francisco",     "CA"),
    "SpaceX":                  ("Southern California", "Hawthorne",         "CA"),
    "Rivian":                  ("Great Plains",        "Normal",            "IL"),
    "Lucid Motors":            ("Northern California", "Newark",            "CA"),
    "Moderna":                 ("New England",         "Cambridge",         "MA"),
    "Pfizer":                  ("Northeast",           "New York",          "NY"),
    "BioNTech":                ("Northeast",           "New York",          "NY"),
    "Regeneron":               ("Northeast",           "Tarrytown",         "NY"),
    "Illumina":                ("Southern California", "San Diego",         "CA"),
    "Equinix":                 ("Northern California", "Redwood City",      "CA"),
    "Digital Realty":          ("Northern California", "San Francisco",     "CA"),
    "Iron Mountain":           ("New England",         "Boston",            "MA"),
    "American Tower":          ("New England",         "Boston",            "MA"),
    "Crown Castle":            ("Texas",               "Houston",           "TX"),

    # ── Extended: Cybersecurity / Tech ──────────────────────────────────────────
    "Palo Alto Networks":      ("Northern California", "Santa Clara",       "CA"),
    "Fortinet":                ("Northern California", "Sunnyvale",         "CA"),
    "Check Point Software":    ("Northern California", "San Carlos",        "CA"),
    "Qualys":                  ("Northern California", "Foster City",       "CA"),
    "Tenable":                 ("Mid-Atlantic",        "Columbia",          "MD"),
    "Rapid7":                  ("New England",         "Boston",            "MA"),
    "SentinelOne":             ("Northern California", "Mountain View",     "CA"),
    "Trellix":                 ("Northern California", "San Jose",          "CA"),
    "Secureworks":             ("Southeast",           "Atlanta",           "GA"),
    "Varonis":                 ("Northeast",           "New York",          "NY"),
    "Sailpoint":               ("Texas",               "Austin",            "TX"),
    "Ping Identity":           ("Mountain",            "Denver",            "CO"),
    "F5 Networks":             ("Northwest",           "Seattle",           "WA"),
    "Juniper Networks":        ("Northern California", "Sunnyvale",         "CA"),
    "Arista Networks":         ("Northern California", "Santa Clara",       "CA"),
    "Pure Storage":            ("Northern California", "Mountain View",     "CA"),
    "NetApp":                  ("Northern California", "San Jose",          "CA"),
    "Commvault":               ("Northeast",           "Tinton Falls",      "NJ"),
    "Elastic":                 ("Northern California", "San Francisco",     "CA"),
    "New Relic":               ("Northern California", "San Francisco",     "CA"),
    "Dynatrace":               ("New England",         "Waltham",           "MA"),
    "PagerDuty":               ("Northern California", "San Francisco",     "CA"),
    "Workday":                 ("Northern California", "Pleasanton",        "CA"),
    "Informatica":             ("Northern California", "Redwood City",      "CA"),
    "Boomi":                   ("Northeast",           "Berwyn",            "PA"),
    "Databricks":              ("Northern California", "San Francisco",     "CA"),
    "Confluent":               ("Northern California", "Mountain View",     "CA"),
    "HashiCorp":               ("Northern California", "San Francisco",     "CA"),
    "Lacework":                ("Northern California", "Mountain View",     "CA"),
    "Orca Security":           ("Northern California", "Palo Alto",         "CA"),
    "Wiz":                     ("Northeast",           "New York",          "NY"),
    "Snyk":                    ("New England",         "Boston",            "MA"),
    "JFrog":                   ("Northern California", "Sunnyvale",         "CA"),
    "Veracode":                ("New England",         "Burlington",        "MA"),
    "Aqua Security":           ("Northeast",           "Hoboken",           "NJ"),
    "Illumio":                 ("Northern California", "Sunnyvale",         "CA"),
    "Exabeam":                 ("Northern California", "Foster City",       "CA"),
    "LogRhythm":               ("Mountain",            "Boulder",           "CO"),
    "Sumo Logic":              ("Northern California", "Redwood City",      "CA"),

    # ── Extended: Financial Services ────────────────────────────────────────────
    "Citigroup":               ("Northeast",           "New York",          "NY"),
    "Bank of America":         ("Southeast",           "Charlotte",         "NC"),
    "Capital One":             ("Mid-Atlantic",        "McLean",            "VA"),
    "US Bancorp":              ("Great Plains",        "Minneapolis",       "MN"),
    "PNC Financial":           ("Northeast",           "Pittsburgh",        "PA"),
    "Charles Schwab":          ("Texas",               "Westlake",          "TX"),
    "Fidelity Investments":    ("New England",         "Boston",            "MA"),
    "T. Rowe Price":           ("Mid-Atlantic",        "Baltimore",         "MD"),
    "Invesco":                 ("Southeast",           "Atlanta",           "GA"),
    "Raymond James":           ("Southeast",           "St. Petersburg",    "FL"),
    "Ameriprise Financial":    ("Great Plains",        "Minneapolis",       "MN"),
    "Lincoln Financial":       ("Northeast",           "Radnor",            "PA"),
    "Principal Financial":     ("Great Plains",        "Des Moines",        "IA"),
    "Truist Financial":        ("Southeast",           "Charlotte",         "NC"),
    "Ally Financial":          ("Great Plains",        "Detroit",           "MI"),
    "Synchrony Financial":     ("New England",         "Stamford",          "CT"),
    "Discover Financial":      ("Great Plains",        "Riverwoods",        "IL"),
    "Regions Financial":       ("Southeast",           "Birmingham",        "AL"),
    "KeyCorp":                 ("Great Plains",        "Cleveland",         "OH"),
    "Fifth Third Bank":        ("Great Plains",        "Cincinnati",        "OH"),

    # ── Extended: Healthcare ─────────────────────────────────────────────────────
    "HCA Healthcare":          ("Southeast",           "Nashville",         "TN"),
    "CommonSpirit Health":     ("Mountain",            "Englewood",         "CO"),
    "Ascension Health":        ("Great Plains",        "St. Louis",         "MO"),
    "Kaiser Permanente":       ("Northern California", "Oakland",           "CA"),
    "Mayo Clinic":             ("Great Plains",        "Rochester",         "MN"),
    "Cleveland Clinic":        ("Great Plains",        "Cleveland",         "OH"),
    "Atrium Health":           ("Southeast",           "Charlotte",         "NC"),
    "Sutter Health":           ("Northern California", "Sacramento",        "CA"),
    "Becton Dickinson":        ("Northeast",           "Franklin Lakes",    "NJ"),
    "Baxter International":    ("Great Plains",        "Deerfield",         "IL"),
    "Boston Scientific":       ("New England",         "Marlborough",       "MA"),
    "Edwards Lifesciences":    ("Southern California", "Irvine",            "CA"),
    "Zimmer Biomet":           ("Great Plains",        "Warsaw",            "IN"),
    "Cardinal Health":         ("Great Plains",        "Dublin",            "OH"),
    "McKesson":                ("Texas",               "Irving",            "TX"),
    "Cerner (Oracle Health)":  ("Great Plains",        "North Kansas City", "MO"),
    "Epic Systems":            ("Great Plains",        "Verona",            "WI"),
    "Inovalon":                ("Mid-Atlantic",        "Bowie",             "MD"),
    "Veeva Systems":           ("Northern California", "Pleasanton",        "CA"),
    "Iqvia":                   ("Southeast",           "Durham",            "NC"),

    # ── Extended: Manufacturing / Industrial ─────────────────────────────────────
    "3M":                      ("Great Plains",        "Saint Paul",        "MN"),
    "Parker Hannifin":         ("Great Plains",        "Mayfield Heights",  "OH"),
    "Emerson Electric":        ("Great Plains",        "St. Louis",         "MO"),
    "Eaton Corporation":       ("Great Plains",        "Dublin",            "OH"),
    "Illinois Tool Works":     ("Great Plains",        "Glenview",          "IL"),
    "Rockwell Automation":     ("Great Plains",        "Milwaukee",         "WI"),
    "Fortive":                 ("Northwest",           "Everett",           "WA"),
    "Roper Technologies":      ("New England",         "Brookfield",        "CT"),
    "Xylem":                   ("Northeast",           "White Plains",      "NY"),
    "Chart Industries":        ("Southeast",           "Ball Ground",       "GA"),

    # ── Extended: Retail / Consumer ──────────────────────────────────────────────
    "Target Corporation":      ("Great Plains",        "Minneapolis",       "MN"),
    "Kroger":                  ("Great Plains",        "Cincinnati",        "OH"),
    "Albertsons":              ("Northwest",           "Boise",             "ID"),
    "Macy's":                  ("Northeast",           "New York",          "NY"),
    "Nordstrom":               ("Northwest",           "Seattle",           "WA"),
    "Gap Inc":                 ("Northern California", "San Francisco",     "CA"),
    "PVH Corp":                ("Northeast",           "New York",          "NY"),
    "Dollar General":          ("Southeast",           "Goodlettsville",    "TN"),
    "Dollar Tree":             ("Mid-Atlantic",        "Chesapeake",        "VA"),
    "AutoZone":                ("Southeast",           "Memphis",           "TN"),

    # ── Extended: Energy / Utilities ─────────────────────────────────────────────
    "Duke Energy":             ("Southeast",           "Charlotte",         "NC"),
    "Southern Company":        ("Southeast",           "Atlanta",           "GA"),
    "Dominion Energy":         ("Mid-Atlantic",        "Richmond",          "VA"),
    "American Electric Power": ("Great Plains",        "Columbus",          "OH"),
    "Exelon":                  ("Great Plains",        "Chicago",           "IL"),
    "NRG Energy":              ("Texas",               "Houston",           "TX"),
    "Entergy":                 ("Southeast",           "New Orleans",       "LA"),
    "Eversource Energy":       ("New England",         "Springfield",       "MA"),
    "Ameren":                  ("Great Plains",        "St. Louis",         "MO"),
    "CenterPoint Energy":      ("Texas",               "Houston",           "TX"),

    # ── Extended: Aerospace & Defense ────────────────────────────────────────────
    "Northrop Grumman":        ("Mid-Atlantic",        "Falls Church",      "VA"),
    "Raytheon Technologies":   ("New England",         "Waltham",           "MA"),
    "General Dynamics":        ("Mid-Atlantic",        "Reston",            "VA"),
    "L3Harris Technologies":   ("Southeast",           "Melbourne",         "FL"),
    "SAIC":                    ("Mid-Atlantic",        "Reston",            "VA"),
    "Leidos":                  ("Mid-Atlantic",        "Reston",            "VA"),
    "Booz Allen Hamilton":     ("Mid-Atlantic",        "McLean",            "VA"),
    "CACI International":      ("Mid-Atlantic",        "Reston",            "VA"),
    "ManTech International":   ("Mid-Atlantic",        "Herndon",           "VA"),
    "Maximus":                 ("Mid-Atlantic",        "Reston",            "VA"),

    # ── Extended: Professional Services ──────────────────────────────────────────
    "Deloitte":                ("Northeast",           "New York",          "NY"),
    "PricewaterhouseCoopers":  ("Northeast",           "New York",          "NY"),
    "EY":                      ("Northeast",           "New York",          "NY"),
    "KPMG":                    ("Northeast",           "New York",          "NY"),
    "Gartner":                 ("New England",         "Stamford",          "CT"),
    "Cognizant":               ("Northeast",           "Teaneck",           "NJ"),
    "Infosys":                 ("Southeast",           "Atlanta",           "GA"),
    "Wipro":                   ("Southeast",           "Atlanta",           "GA"),
    "Tata Consultancy":        ("Northeast",           "New York",          "NY"),
    "Capgemini":               ("Northeast",           "New York",          "NY"),

    # ── Extended: Telecommunications ─────────────────────────────────────────────
    "T-Mobile":                ("Northwest",           "Bellevue",          "WA"),
    "Lumen Technologies":      ("Southeast",           "Monroe",            "LA"),
    "RingCentral":             ("Northern California", "Belmont",           "CA"),
    "Vonage":                  ("Northeast",           "Holmdel",           "NJ"),
    "8x8":                     ("Northern California", "Campbell",          "CA"),
    "Bandwidth":               ("Southeast",           "Raleigh",           "NC"),
    "Zayo Group":              ("Mountain",            "Boulder",           "CO"),
    "Windstream":              ("Southeast",           "Little Rock",       "AR"),
    "Consolidated Comm.":      ("Great Plains",        "Mattoon",           "IL"),
    "Iridium Communications":  ("Mid-Atlantic",        "McLean",            "VA"),

    # ── Extended: Logistics / Transportation ─────────────────────────────────────
    "FedEx":                   ("Southeast",           "Memphis",           "TN"),
    "UPS":                     ("Southeast",           "Atlanta",           "GA"),
    "XPO Logistics":           ("New England",         "Greenwich",         "CT"),
    "J.B. Hunt":               ("Southeast",           "Lowell",            "AR"),
    "C.H. Robinson":           ("Great Plains",        "Eden Prairie",      "MN"),
    "Ryder System":            ("Southeast",           "Miami",             "FL"),
    "Werner Enterprises":      ("Great Plains",        "Omaha",             "NE"),
    "Landstar System":         ("Southeast",           "Jacksonville",      "FL"),
    "Old Dominion Freight":    ("Southeast",           "Thomasville",       "NC"),
}
